//! Default seed data for all database backends.
//!
//! These constants define the initial model mappings and feature flags
//! that are inserted during `initialize()`. Each backend consumes
//! these definitions through the `seed_defaults()` default method on
//! `DatabaseService`.

use std::time::{SystemTime, UNIX_EPOCH};

use super::models::*;

fn unix_now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock before UNIX epoch")
        .as_secs() as i64
}

/// Default model mappings (source model ID -> target provider model ID).
pub fn default_model_mappings() -> Vec<ModelMappingRecord> {
    let now = unix_now();
    vec![
        ModelMappingRecord {
            source_model_id: "claude-3-5-sonnet-20241022".into(),
            target_model_id: "anthropic.claude-3-5-sonnet-20241022-v2:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude 3.5 Sonnet".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-5-sonnet-latest".into(),
            target_model_id: "anthropic.claude-3-5-sonnet-20241022-v2:0".into(),
            provider: "bedrock".into(),
            display_name: "".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-sonnet-20240229".into(),
            target_model_id: "anthropic.claude-3-sonnet-20240229-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-sonnet-4-20250514".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-20250514-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude Sonnet 4".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-5-haiku-20241022".into(),
            target_model_id: "anthropic.claude-3-5-haiku-20241022-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude 3.5 Haiku".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-haiku-20240307".into(),
            target_model_id: "anthropic.claude-3-haiku-20240307-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-opus-20240229".into(),
            target_model_id: "anthropic.claude-3-opus-20240229-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude 3 Opus".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-opus-4-5-20251101".into(),
            target_model_id: "global.anthropic.claude-opus-4-5-20251101-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude Opus 4.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-sonnet-4-6-20260313".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "Claude Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-opus-4-6-20260313".into(),
            target_model_id: "global.anthropic.claude-opus-4-6-v1".into(),
            provider: "bedrock".into(),
            display_name: "Claude Opus 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-haiku-4-5-20251001".into(),
            target_model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude Haiku 4.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // -latest aliases (Claude)
        ModelMappingRecord {
            source_model_id: "claude-sonnet-4-latest".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "Claude Sonnet 4 Latest".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-opus-4-latest".into(),
            target_model_id: "global.anthropic.claude-opus-4-6-v1".into(),
            provider: "bedrock".into(),
            display_name: "Claude Opus 4 Latest".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-haiku-4-latest".into(),
            target_model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude Haiku 4 Latest".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-5-haiku-latest".into(),
            target_model_id: "anthropic.claude-3-5-haiku-20241022-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude 3.5 Haiku Latest".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "claude-3-opus-latest".into(),
            target_model_id: "anthropic.claude-3-opus-20240229-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "Claude 3 Opus Latest".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // Gemini exact mappings (passthrough: target = source)
        ModelMappingRecord {
            source_model_id: "gemini-2.5-flash".into(),
            target_model_id: "gemini-2.5-flash".into(),
            provider: "gemini".into(),
            display_name: "Gemini 2.5 Flash".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gemini-2.5-pro".into(),
            target_model_id: "gemini-2.5-pro".into(),
            provider: "gemini".into(),
            display_name: "Gemini 2.5 Pro".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gemini-2.0-flash".into(),
            target_model_id: "gemini-2.0-flash".into(),
            provider: "gemini".into(),
            display_name: "Gemini 2.0 Flash".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gemini-2.0-flash-lite".into(),
            target_model_id: "gemini-2.0-flash-lite".into(),
            provider: "gemini".into(),
            display_name: "Gemini 2.0 Flash Lite".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gemini-1.5-pro".into(),
            target_model_id: "gemini-1.5-pro".into(),
            provider: "gemini".into(),
            display_name: "Gemini 1.5 Pro".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gemini-1.5-flash".into(),
            target_model_id: "gemini-1.5-flash".into(),
            provider: "gemini".into(),
            display_name: "Gemini 1.5 Flash".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // OpenAI-compatible exact mappings (GPT → Bedrock Claude)
        ModelMappingRecord {
            source_model_id: "gpt-4o".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4o → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4o-2024-05-13".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4o 2024-05-13 → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4o-2024-08-06".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4o 2024-08-06 → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4o-mini".into(),
            target_model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4o Mini → Haiku 4.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4o-mini-2024-07-18".into(),
            target_model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4o Mini 2024-07-18 → Haiku 4.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4 → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4-turbo".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4 Turbo → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-4-turbo-preview".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT-4 Turbo Preview → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-3.5-turbo".into(),
            target_model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "GPT-3.5 Turbo → Haiku 4.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "gpt-3.5-turbo-16k".into(),
            target_model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
            provider: "bedrock".into(),
            display_name: "GPT-3.5 Turbo 16K → Haiku 4.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "o1".into(),
            target_model_id: "global.anthropic.claude-opus-4-6-v1".into(),
            provider: "bedrock".into(),
            display_name: "O1 → Opus 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "o1-preview".into(),
            target_model_id: "global.anthropic.claude-opus-4-6-v1".into(),
            provider: "bedrock".into(),
            display_name: "O1 Preview → Opus 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "o1-mini".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "O1 Mini → Sonnet 4.6".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // ── Embedding models (Bedrock InvokeModel) ──────────────────────────
        // Cohere Embed v3
        ModelMappingRecord {
            source_model_id: "cohere.embed-english-v3".into(),
            target_model_id: "cohere.embed-english-v3".into(),
            provider: "bedrock".into(),
            display_name: "Cohere Embed English v3".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "cohere.embed-multilingual-v3".into(),
            target_model_id: "cohere.embed-multilingual-v3".into(),
            provider: "bedrock".into(),
            display_name: "Cohere Embed Multilingual v3".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // Titan Embed
        ModelMappingRecord {
            source_model_id: "amazon.titan-embed-text-v2:0".into(),
            target_model_id: "amazon.titan-embed-text-v2:0".into(),
            provider: "bedrock".into(),
            display_name: "Amazon Titan Embed Text v2".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "amazon.titan-embed-text-v1".into(),
            target_model_id: "amazon.titan-embed-text-v1".into(),
            provider: "bedrock".into(),
            display_name: "Amazon Titan Embed Text v1".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // OpenAI text-embedding aliases → Titan Embed v2
        ModelMappingRecord {
            source_model_id: "text-embedding-3-small".into(),
            target_model_id: "amazon.titan-embed-text-v2:0".into(),
            provider: "bedrock".into(),
            display_name: "text-embedding-3-small → Titan Embed v2".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "text-embedding-3-large".into(),
            target_model_id: "amazon.titan-embed-text-v2:0".into(),
            provider: "bedrock".into(),
            display_name: "text-embedding-3-large → Titan Embed v2".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "text-embedding-ada-002".into(),
            target_model_id: "amazon.titan-embed-text-v2:0".into(),
            provider: "bedrock".into(),
            display_name: "text-embedding-ada-002 → Titan Embed v2".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // ── Rerank models (Bedrock InvokeModel) ─────────────────────────────
        ModelMappingRecord {
            source_model_id: "cohere.rerank-v3-5:0".into(),
            target_model_id: "cohere.rerank-v3-5:0".into(),
            provider: "bedrock".into(),
            display_name: "Cohere Rerank v3.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "rerank-english-v3.0".into(),
            target_model_id: "cohere.rerank-v3-5:0".into(),
            provider: "bedrock".into(),
            display_name: "rerank-english-v3.0 → Cohere Rerank v3.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        ModelMappingRecord {
            source_model_id: "rerank-multilingual-v3.0".into(),
            target_model_id: "cohere.rerank-v3-5:0".into(),
            provider: "bedrock".into(),
            display_name: "rerank-multilingual-v3.0 → Cohere Rerank v3.5".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: 0,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // Wildcard catch-all: any claude-* model not matched above
        ModelMappingRecord {
            source_model_id: "claude-*".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "Claude Wildcard (default to Sonnet 4.6)".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: -100,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // Wildcard catch-all: any gemini-* model not matched above
        ModelMappingRecord {
            source_model_id: "gemini-*".into(),
            target_model_id: "gemini-2.5-flash".into(),
            provider: "gemini".into(),
            display_name: "Gemini Wildcard (default to 2.5 Flash)".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: -100,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // Wildcard catch-all: any gpt-* model not matched above
        ModelMappingRecord {
            source_model_id: "gpt-*".into(),
            target_model_id: "global.anthropic.claude-sonnet-4-6".into(),
            provider: "bedrock".into(),
            display_name: "GPT Wildcard (default to Sonnet 4.6)".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: -100,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
        // Wildcard catch-all: any o1-* model not matched above
        ModelMappingRecord {
            source_model_id: "o1-*".into(),
            target_model_id: "global.anthropic.claude-opus-4-6-v1".into(),
            provider: "bedrock".into(),
            display_name: "O1 Wildcard (default to Opus 4.6)".into(),
            input_price: 0.0,
            output_price: 0.0,
            cache_read_price: 0.0,
            cache_write_price: 0.0,
            priority: -100,
            status: "active".into(),
            created_at: now,
            updated_at: None,
        },
    ]
}

/// Default system settings (insert-if-not-exists on startup).
pub fn default_system_settings() -> Vec<SystemSettingRecord> {
    vec![
        SystemSettingRecord {
            key: "default_cache_ttl".into(),
            value: "".into(),
            description:
                "Default prompt cache TTL for Bedrock requests. Values: '' (disabled), '5m', '1h'."
                    .into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "enable_tool_use".into(),
            value: "true".into(),
            description: "Enable tool use / function calling support.".into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "enable_ptc".into(),
            value: "false".into(),
            description: "Enable Programmatic Tool Calling (PTC) sandbox execution.".into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "enable_extended_thinking".into(),
            value: "true".into(),
            description: "Enable extended thinking (Claude budget_tokens support).".into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "enable_document_support".into(),
            value: "true".into(),
            description: "Enable document content blocks in requests.".into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "prompt_caching_enabled".into(),
            value: "false".into(),
            description: "Deprecated: use prompt_cache instead.".into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "prompt_cache".into(),
            value: "passthrough".into(),
            description: "Prompt cache behavior for Bedrock InvokeModel (Claude) requests. \
                          'disable' strips all cache_control, 'passthrough' preserves as-is, \
                          '5m'/'1h' overrides TTL on all cache_control blocks."
                .into(),
            updated_at: None,
        },
        SystemSettingRecord {
            key: "rate_limit_enabled".into(),
            value: "true".into(),
            description: "Enable per-key request rate limiting (RPM).".into(),
            updated_at: None,
        },
    ]
}
